(ns base16-matrix.parse
  (:require [clojure.string :as str]
            [clojure.spec.alpha :as s]))

(s/def ::-hex-color (s/and string? (partial re-matches #"[0-9a-fA-F]{6}")))
(s/def ::scheme (s/and string? (partial not= "")))
(s/def ::author string?)
(s/def ::base00 ::-hex-color)
(s/def ::base01 ::-hex-color)
(s/def ::base02 ::-hex-color)
(s/def ::base03 ::-hex-color)
(s/def ::base04 ::-hex-color)
(s/def ::base05 ::-hex-color)
(s/def ::base06 ::-hex-color)
(s/def ::base07 ::-hex-color)
(s/def ::base08 ::-hex-color)
(s/def ::base09 ::-hex-color)
(s/def ::base0A ::-hex-color)
(s/def ::base0B ::-hex-color)
(s/def ::base0C ::-hex-color)
(s/def ::base0D ::-hex-color)
(s/def ::base0E ::-hex-color)
(s/def ::base0F ::-hex-color)
(s/def ::theme (s/keys :req-un [::scheme ::author ::base00 ::base01 ::base02 ::base03 ::base04 ::base05 ::base06 ::base07 ::base08 ::base09 ::base0A ::base0B ::base0C ::base0D ::base0E ::base0F]))
